[theme]
base = "dark"
primaryColor = "#e08850"
backgroundColor = "#0d1321"
secondaryBackgroundColor = "#161e2e"
textColor = "#dbe2ec"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"

[client]
toolbarMode = "minimal"
